namespace DatabaseManager.Model
{
    public partial class Sumtaskspread
    {
        public long? ProjId { get; set; }
        public long? WbsId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string? SpreadType { get; set; }
        public double? Acwp { get; set; }
        public double? ActCost { get; set; }
        public double? ActEquipCost { get; set; }
        public double? ActExpenseCost { get; set; }
        public double? ActMatCost { get; set; }
        public double? ActWorkCost { get; set; }
        public double? ActEquipQty { get; set; }
        public double? ActWorkQty { get; set; }
        public double? BaseCost { get; set; }
        public double? BaseEquipCost { get; set; }
        public double? BaseExpenseCost { get; set; }
        public double? BaseMatCost { get; set; }
        public double? BaseWorkCost { get; set; }
        public double? BaseEquipQty { get; set; }
        public double? BaseWorkQty { get; set; }
        public double? LateRemainCost { get; set; }
        public double? LateRemainEquipCost { get; set; }
        public double? LateRemainExpenseCost { get; set; }
        public double? LateRemainMatCost { get; set; }
        public double? LateRemainWorkCost { get; set; }
        public double? LateRemainEquipQty { get; set; }
        public double? LateRemainWorkQty { get; set; }
        public double? RemainCost { get; set; }
        public double? RemainEquipCost { get; set; }
        public double? RemainExpenseCost { get; set; }
        public double? RemainMatCost { get; set; }
        public double? RemainWorkCost { get; set; }
        public double? RemainEquipQty { get; set; }
        public double? RemainWorkQty { get; set; }
        public double? TargetCost { get; set; }
        public double? TargetEquipCost { get; set; }
        public double? TargetExpenseCost { get; set; }
        public double? TargetMatCost { get; set; }
        public double? TargetWorkCost { get; set; }
        public double? TargetEquipQty { get; set; }
        public double? TargetWorkQty { get; set; }
        public double? TotalCost { get; set; }
        public double? TotalEquipCost { get; set; }
        public double? TotalExpenseCost { get; set; }
        public double? TotalMatCost { get; set; }
        public double? TotalWorkCost { get; set; }
        public double? TotalEquipQty { get; set; }
        public double? TotalWorkQty { get; set; }
        public double? Bcwp { get; set; }
        public double? Bcws { get; set; }
        public double? Eac { get; set; }
        public double? EacWork { get; set; }
        public double? Etc { get; set; }
        public double? EtcWorkQty { get; set; }
        public double? PerfmWorkQty { get; set; }
        public double? SchedWorkQty { get; set; }
        public double? FinPeriodActWorkQty { get; set; }
        public double? FinPeriodActWorkCost { get; set; }
        public double? FinPeriodActEquipQty { get; set; }
        public double? FinPeriodActEquipCost { get; set; }
        public double? FinPeriodActMatCost { get; set; }
        public double? FinPeriodActExpenseCost { get; set; }
        public double? FinPeriodTotalWorkQty { get; set; }
        public double? FinPeriodTotalWorkCost { get; set; }
        public double? FinPeriodTotalEquipQty { get; set; }
        public double? FinPeriodTotalEquipCost { get; set; }
        public double? FinPeriodTotalMatCost { get; set; }
        public double? FinPeriodTotalExpenseCost { get; set; }
        public double? FinPeriodTotalCost { get; set; }
        public double? FinPeriodActCost { get; set; }
        public double? FinPeriodBcwp { get; set; }
        public double? FinPeriodPerfmWorkQty { get; set; }
        public double? FinPeriodEac { get; set; }
        public double? FinPeriodEacWork { get; set; }
        public double? FinPeriodEacWorkQty { get; set; }
        public double? FinPeriodBcws { get; set; }
        public double? FinPeriodSchedWorkQty { get; set; }
        public double? EacWorkQty { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? CreateUser { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string? UpdateUser { get; set; }
        public long? DeleteSessionId { get; set; }
        public DateTime? DeleteDate { get; set; }
    }
}
