using System.Windows;

namespace XerParser
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, System.EventArgs e)
        {

        }
    }
}
